## Exercise 1

Take several pictures of red, blue, and green items with your phone or other digital camera (or download some from the internet, if a camera isn’t available).

In [8]:
import imageio

im = imageio.imread('biege.jpeg')
print(im.shape)


(1156, 867, 3)


In [9]:
im

Array([[[133, 133, 131],
        [133, 133, 131],
        [133, 133, 131],
        ...,
        [140, 140, 138],
        [140, 140, 138],
        [140, 140, 138]],

       [[133, 133, 131],
        [133, 133, 131],
        [133, 133, 131],
        ...,
        [140, 140, 138],
        [140, 140, 138],
        [140, 140, 138]],

       [[133, 133, 131],
        [133, 133, 131],
        [133, 133, 131],
        ...,
        [141, 141, 139],
        [141, 141, 139],
        [141, 141, 139]],

       ...,

       [[105, 111, 109],
        [113, 119, 117],
        [113, 117, 116],
        ...,
        [109, 110, 105],
        [109, 110, 105],
        [109, 110, 105]],

       [[105, 111, 109],
        [114, 120, 118],
        [113, 117, 116],
        ...,
        [108, 109, 104],
        [108, 109, 104],
        [108, 109, 104]],

       [[106, 112, 110],
        [115, 121, 119],
        [114, 118, 117],
        ...,
        [107, 108, 103],
        [107, 108, 103],
        [107, 108, 103]]

Load each image, and convert it to a tensor.

In [10]:
import torch
im_tensor = torch.from_numpy(im)

In [11]:
type(im_tensor)

torch.Tensor

In [12]:
im_tensor

tensor([[[133, 133, 131],
         [133, 133, 131],
         [133, 133, 131],
         ...,
         [140, 140, 138],
         [140, 140, 138],
         [140, 140, 138]],

        [[133, 133, 131],
         [133, 133, 131],
         [133, 133, 131],
         ...,
         [140, 140, 138],
         [140, 140, 138],
         [140, 140, 138]],

        [[133, 133, 131],
         [133, 133, 131],
         [133, 133, 131],
         ...,
         [141, 141, 139],
         [141, 141, 139],
         [141, 141, 139]],

        ...,

        [[105, 111, 109],
         [113, 119, 117],
         [113, 117, 116],
         ...,
         [109, 110, 105],
         [109, 110, 105],
         [109, 110, 105]],

        [[105, 111, 109],
         [114, 120, 118],
         [113, 117, 116],
         ...,
         [108, 109, 104],
         [108, 109, 104],
         [108, 109, 104]],

        [[106, 112, 110],
         [115, 121, 119],
         [114, 118, 117],
         ...,
         [107, 108, 103],
        

For each image tensor, use the .mean() method to get a sense of how bright
the image is.

In [14]:
im_tensor = im_tensor.float()

In [15]:
im_tensor.mean()

tensor(123.6675)

Take the mean of each channel of your images. Can you identify the red,
green, and blue items from only the channel averages?

In [16]:
im_tensor.shape

torch.Size([1156, 867, 3])

In [21]:
n_channels = im_tensor.shape[2]

In [22]:
n_channels

3

In [24]:
im_tensor[:,:,0]

tensor([[133., 133., 133.,  ..., 140., 140., 140.],
        [133., 133., 133.,  ..., 140., 140., 140.],
        [133., 133., 133.,  ..., 141., 141., 141.],
        ...,
        [105., 113., 113.,  ..., 109., 109., 109.],
        [105., 114., 113.,  ..., 108., 108., 108.],
        [106., 115., 114.,  ..., 107., 107., 107.]])

In [26]:
for i in range(3):
  print(i," : ", im_tensor[:,:,i].mean())


0  :  tensor(124.6178)
1  :  tensor(124.0964)
2  :  tensor(122.2884)


In [27]:
red = imageio.imread('red.jpeg')
red_tensor = torch.from_numpy(red)

In [28]:
red_tensor = red_tensor.float()

for i in range(3):
  print(i, " : ", red_tensor[:,:,i].mean())

# thereis definitely a differnece in the red component

0  :  tensor(188.9327)
1  :  tensor(58.0965)
2  :  tensor(97.3570)


## Exercise 2

Select a relatively large file containing Python source code.

In [40]:
f1 = open('mandel.py', 'r+')

In [41]:
text = f1.read()

In [35]:
f1.readlines()

['from pylab import * \n',
 'from numpy import NaN \n',
 '  \n',
 'def m(a): \n',
 '\tz = 0 \n',
 '\tfor n in range(1, 100): \n',
 '\t\tz = z**2 + a \n',
 '\t\tif abs(z) > 2: \n',
 '\t\t\treturn n \n',
 '\treturn NaN \n',
 '  \n',
 'X = arange(-2, .5, .002) \n',
 'Y = arange(-1,  1, .002) \n',
 'Z = zeros((len(Y), len(X))) \n',
 '  \n',
 'for iy, y in enumerate(Y): \n',
 '\tprint (iy, "of", len(Y)) \n',
 '\tfor ix, x in enumerate(X): \n',
 '\t\tZ[iy,ix] = m(x + 1j * y) \n',
 '  \n',
 "imshow(Z, cmap = plt.cm.prism, interpolation = 'none', extent = (X.min(), X.max(), Y.min(), Y.max())) \n",
 'xlabel("Re(c)") \n',
 'ylabel("Im(c)") \n',
 'savefig("mandelbrot_python.jpeg") \n',
 'show() ']

Build an index of all the words in the source file (feel free to make your tokenization as simple or as complex as you like; we suggest starting with replacing r"[^a-zA-Z0-9_]+" with spaces)

In [42]:
text

'from pylab import * \nfrom numpy import NaN \n  \ndef m(a): \n\tz = 0 \n\tfor n in range(1, 100): \n\t\tz = z**2 + a \n\t\tif abs(z) > 2: \n\t\t\treturn n \n\treturn NaN \n  \nX = arange(-2, .5, .002) \nY = arange(-1,  1, .002) \nZ = zeros((len(Y), len(X))) \n  \nfor iy, y in enumerate(Y): \n\tprint (iy, "of", len(Y)) \n\tfor ix, x in enumerate(X): \n\t\tZ[iy,ix] = m(x + 1j * y) \n  \nimshow(Z, cmap = plt.cm.prism, interpolation = \'none\', extent = (X.min(), X.max(), Y.min(), Y.max())) \nxlabel("Re(c)") \nylabel("Im(c)") \nsavefig("mandelbrot_python.jpeg") \nshow() '

In [44]:
lines = text.split('\n')
lines[4]

'\tz = 0 '

In [54]:
clean_lines = []
for line in lines:
  punctuation = r"[^a-zA-Z0-9_]+"
  wordlist = line.lower().replace('\n', ' ').split()
  wordlist = [word.strip(punctuation) for word in wordlist]
  clean_lines.append(wordlist) 

In [55]:
clean_lines[4]

['', '=', '']

In [56]:
clean_lines

[['from', 'pylab', 'import', '*'],
 ['from', 'numpy', 'import', 'nan'],
 [],
 ['def', 'm(a):'],
 ['', '=', ''],
 ['for', 'n', 'in', 'range(1,', '100):'],
 ['', '=', '**2', '', ''],
 ['if', 'bs(z)', '>', '2:'],
 ['return', 'n'],
 ['return', 'nan'],
 [],
 ['x', '=', 'range(-2,', '.5,', '.002)'],
 ['y', '=', 'range(-1,', '1,', '.002)'],
 ['', '=', 'eros((len(y),', 'len(x)))'],
 [],
 ['for', 'iy,', 'y', 'in', 'enumerate(y):'],
 ['print', '(iy,', '"of",', 'len(y))'],
 ['for', 'ix,', 'x', 'in', 'enumerate(x):'],
 ['iy,ix', '=', 'm(x', '', '1j', '*', 'y)'],
 [],
 ['imshow(z,',
  'cmap',
  '=',
  'plt.cm.prism,',
  'interpolation',
  '=',
  "'none',",
  'extent',
  '=',
  '(x.min(),',
  'x.max(),',
  'y.min(),',
  'y.max()))'],
 ['xlabel("re(c)")'],
 ['ylabel("im(c)")'],
 ['savefig("mandelbrot_python.jpeg")'],
 ['show()']]

In [57]:
wordlist = text.lower().replace('\n', ' ').split()
wordlist = [word.strip(punctuation) for word in wordlist]
wordlist = sorted(set(wordlist))
wordlist

['',
 '"of",',
 "'none',",
 '(iy,',
 '(x.min(),',
 '*',
 '**2',
 '.002)',
 '.5,',
 '1,',
 '100):',
 '1j',
 '2:',
 '=',
 '>',
 'bs(z)',
 'cmap',
 'def',
 'enumerate(x):',
 'enumerate(y):',
 'eros((len(y),',
 'extent',
 'for',
 'from',
 'if',
 'import',
 'imshow(z,',
 'in',
 'interpolation',
 'ix,',
 'iy,',
 'iy,ix',
 'len(x)))',
 'len(y))',
 'm(a):',
 'm(x',
 'n',
 'nan',
 'numpy',
 'plt.cm.prism,',
 'print',
 'pylab',
 'range(-1,',
 'range(-2,',
 'range(1,',
 'return',
 'savefig("mandelbrot_python.jpeg")',
 'show()',
 'x',
 'x.max(),',
 'xlabel("re(c)")',
 'y',
 'y)',
 'y.max()))',
 'y.min(),',
 'ylabel("im(c)")']

Compare your index with the one we made for Pride and Prejudice. Which is
larger?

In [58]:
word2index_dict = {word : i for (i, word) in enumerate(wordlist)}

In [59]:
len(word2index_dict)

# the length of pride and prejudice was 8430

56

Create the one-hot encoding for the source code file.

In [60]:
one_hot = torch.zeros(len(text), 128)
one_hot.shape

torch.Size([533, 128])

In [61]:
for i , letter in enumerate(text.lower().strip()):
  letter_index = ord(letter) if ord(letter) < 128 else 0
  one_hot[i][letter_index] = 1

In [69]:
one_hot[18], text[18]

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]), '*')

What information is lost with this encoding? How does that information
compare to what’s lost in the Pride and Prejudice encoding?

semantic information is lost