# Learning Pytorch
This series would be taken from various tutorial available in youtube.

## 1 : Creating a simple convolutional neural network
This one is taken from excellent channel Alladin Perrson : https://www.youtube.com/watch?v=Jy4wM2X21u0&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=3

![](https://i.morioh.com/200620/5b0ea047.jpg)

## Handling imports

In [107]:
import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import Dataset

## creating the model

In [108]:
class SimpleNN(nn.Module):
    def __init__(self, model_size, num_of_classes):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(model_size, 48)
        self.fc2 = nn.Linear(48, num_of_classes)
    
    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        return out

In [109]:
class SimpleCNN(nn.Module):
    def __init__(self, in_channels=1, classes=10):
        super(SimpleCNN, self).__init__()
        
        self.conv1 = nn.Conv2d(
            in_channels=in_channels,
            out_channels=8, 
            padding=(1,1), 
            kernel_size=(3,3), 
            stride=(1,1)) # same convolution, input will be same as output
        
        self.conv2 = nn.Conv2d(
            in_channels=8, 
            out_channels=16, 
            padding=(1,1), 
            kernel_size=(3,3), 
            stride=(1,1))
        
        self.pool = nn.MaxPool2d(kernel_size=(2,2), stride=(2,2))
        self.fc1 = nn.Linear(16*7*7, classes)
    
    def forward(self, x):
        out = F.relu(self.conv1(x))
        out = self.pool(out)
        out = F.relu(self.conv2(out))
        out = self.pool(out)
        out = out.reshape(out.shape[0], -1)
        out = self.fc1(out)
        return out
        
        

In [110]:
class CNN(nn.Module):
    def __init__(self, in_channels=1, num_classes=10):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(
            in_channels=in_channels,
            out_channels=8,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
        )
        self.pool = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv2 = nn.Conv2d(
            in_channels=8,
            out_channels=16,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
        )
        self.fc1 = nn.Linear(16 * 7 * 7, num_classes)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        x = x.reshape(x.shape[0], -1)
        x = self.fc1(x)
        return x

## Getting device information

In [111]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## Putting in the hyper parameters

In [112]:
num_epochs = 5
learning_rate = 0.001
batch_size=64
# input_size=784
in_channels=1
num_of_classes=10


## Getting the dataset

In [113]:
# try:
#     train_dataset = datasets.MNIST(root='./dataset/', download=True, train=True, transform=transforms.ToTensor())
#     test_dataset = datasets.MNIST(root='./dataset/', download=True, train=False, transform=transforms.ToTensor())
#     train_dataloader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
#     test_dataloader = DataLoader(dataset = test_dataset, batch_size=batch_size, shuffle=True)
# except Exception as e:
#     print(e)
    

since getting a from interenet isn't reliable lets try with a dataset from csv

## Custom data set class

with help from https://www.youtube.com/watch?v=PXOzkkB5eH0

In [114]:
import numpy as np

testing

In [115]:
xy = np.loadtxt('../input/mnist-in-csv/mnist_train.csv', delimiter=",", dtype=np.float32, skiprows=1)
x = xy[:,1:]
y = xy[:,[0]]
print(x, y)
    

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[5.]
 [0.]
 [4.]
 ...
 [5.]
 [6.]
 [8.]]


In [126]:
import pandas as pd

dd = pd.read_csv('../input/mnist-in-csv/mnist_train.csv', dtype=np.float)
dd.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0    5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2    4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 785 columns]

In [127]:
y_dash = torch.from_numpy(dd.iloc[:,0].values) # y
y_dash

tensor([5., 0., 4.,  ..., 5., 6., 8.], dtype=torch.float64)

In [129]:
type(y_dash)

torch.Tensor

In [118]:
dd.shape

(60000, 785)

In [131]:
x_dash = torch.from_numpy(dd.iloc[:,1:].values)

x_dash[0]

tensor([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   

In [132]:
type(x_dash)

torch.Tensor

In [134]:
x_d = x_dash.reshape(x_dash.size(0), 1, 28,28)
x_d.shape

torch.Size([60000, 1, 28, 28])

testing over

In [174]:
import numpy as np

class MnistDataset(Dataset):
    def __init__(self, data_path):
        # data loading
        df = pd.read_csv(data_path, dtype=np.float)
        self.x = torch.from_numpy(df.iloc[:,1:].values)
        
        self.x = self.x.reshape(self.x.size(0),1,28,28)
        self.x = self.x.float() # why float?
        
        self.y = torch.from_numpy(df.iloc[:,0].values) 
        self.y = self.y.long() # why long?
        
        self.n_samples = df.shape[0]
        
    def __len__(self):
        return self.n_samples
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
        

In [175]:
train_dataset = MnistDataset("../input/mnist-in-csv/mnist_train.csv")
train_dataloader = DataLoader(dataset=train_dataset, batch_size=batch_size,shuffle=True)

test_dataset = MnistDataset("../input/mnist-in-csv/mnist_test.csv")
train_dataloader = DataLoader(dataset=test_dataset, batch_size=batch_size,shuffle=True)


We can also look at individual dataset that loaded

In [176]:
first = train_dataset[0]
features, label = first
print(features, label)

tensor([[[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.],
     

In [170]:
type(features)

torch.Tensor

## initialising the model

In [177]:
model = SimpleCNN().to(device=device) # to device?

In [172]:
#testing
x = torch.randn(64,1,28,28).to(device=device)
y = model(x)
y.shape

torch.Size([64, 10])

## Define loss criterion and optimizer

In [163]:
loss_criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

## Train on data

In [178]:
current_loss = 0
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(train_dataloader):
        # Get data to cuda if possible
        data = data.to(device=device)
        targets = targets.to(device=device)
        
#         data = data.reshape((data.shape[0],1,28,28))
#         print(f"data shape: {data.shape}")

        # forward
        scores = model(data)
        loss = loss_criterion(scores, targets)
        current_loss = loss
        
        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent or adam step
        optimizer.step()
    
    print(f"At epoch: {epoch}, loss: {current_loss}")

At epoch: 0, loss: 23.493770599365234
At epoch: 1, loss: 21.50348663330078
At epoch: 2, loss: 29.63482666015625
At epoch: 3, loss: 25.373334884643555
At epoch: 4, loss: 23.500032424926758


In [179]:
def check_accuracy(model, dataloader):
    
    total_sample = 0
    correct_sample = 0
    
    model.eval()
    
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(device=device)
            y = y.to(device=device)
            
#             x = x.reshape(x.shape[0], -1)
            
            scores = model(x)
            _, predictions = scores.max(1)
            correct_sample = (y==predictions).sum()
            total_sample += predictions.size(0)
            
    model.train()
    
    print(f"out of total sample : {total_sample}  correct sample : {correct_sample} accuracy : {float(correct_sample/total_sample)*100:.2f}")
            
    

In [180]:
check_accuracy(model, train_dataloader)
check_accuracy(model, test_dataloader)

out of total sample : 10000  correct sample : 0 accuracy : 0.00
out of total sample : 10000  correct sample : 1 accuracy : 0.01
